#!/usr/bin/env bash
# Render every theme into docs/themes/<name>.png and regenerate docs/themes.md.
# Covers the built-in themes plus any contrib/themes/*.css; run inside 'nix develop' after 'cargo build'.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(dirname "$here")
harness=$here/harness.sh
gallery=$repo/docs/themes.md
export NDW_E2E_OUT=$repo/docs/themes

tmp=$(mktemp -d)
trap '"$harness" stop; rm -rf "$tmp"' EXIT

# Named, created workspaces so the shot shows focused, plain and uncreated cards.
declare -A names=([w]=web [e]=mail [a]=api [s]=shop [d]=docs [c]=chat)

# render <shot> <general.theme value> <GTK_THEME>
render() {
    local shot=$1 theme=$2 key
    {
        sed "s|^\[general\]|[general]\ntheme = \"$theme\"|" "$here/fixtures/config.toml"
        for key in "${!names[@]}"; do
            printf '\n[workspace.%s]\nname = "%s"\n' "$key" "${names[$key]}"
        done
    } >"$tmp/config.toml"

    NDW_E2E_CONFIG=$tmp/config.toml NDW_E2E_GTK_THEME=$3 "$harness" start >/dev/null
    # Last one stays focused.
    for key in w e s d c a; do
        "$harness" app switch "$key"
    done
    "$harness" overlay switch
    "$harness" shot "$shot" >/dev/null
    "$harness" stop
    echo "rendered $shot" >&2
}

# section <title> <shot> <theme value as written in config.toml> [css file to show]
section() {
    printf '\n## %s\n\n```toml\n[general]\ntheme = "%s"\n```\n\n![%s](themes/%s.png)\n' "$1" "$3" "$1" "$2"
    if [[ -n ${4:-} ]]; then
        printf '\n<details>\n<summary><code>%s</code></summary>\n\n```css\n%s\n```\n\n</details>\n' \
            "${4#"$repo"/}" "$(cat "$4")"
    fi
}

rm -rf "$NDW_E2E_OUT"
mkdir -p "$NDW_E2E_OUT"

{
    cat <<'MD'
<!-- Generated by e2e/render-themes.sh; do not edit. -->
# Theme gallery

Set `general.theme` to one of the built-in names, or to the path of a CSS
file. See [Theming](../README.md#theming) for the variables and classes.
MD

    render gtk-dark gtk Default:dark
    section "gtk, under a dark GTK theme" gtk-dark gtk
    render gtk-light gtk Default:light
    section "gtk, under a light GTK theme" gtk-light gtk

    # Against the opposite GTK variant: the built-in palettes must not depend on it.
    render dark dark Default:light
    section dark dark dark "$repo/themes/dark.css"
    render light light Default:dark
    section light light light "$repo/themes/light.css"

    shopt -s nullglob
    for css in "$repo"/contrib/themes/*.css; do
        name=$(basename "$css" .css)
        render "$name" "$css" Default:dark
        section "$name" "$name" "$name.css" "$css"
    done
} >"$gallery.tmp"

mv "$gallery.tmp" "$gallery"
echo "wrote ${gallery#"$repo"/}" >&2
