#!/usr/bin/env bash
# Render every theme in themes/ into docs/themes/<name>.png and regenerate docs/themes.md.
# Run inside 'nix develop' after 'cargo build'.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(dirname "$here")
harness=$here/harness.sh
gallery=$repo/docs/themes.md
shots=$repo/docs/themes

# Everything lands in a scratch dir first, so a failed run leaves docs/ untouched.
tmp=$(mktemp -d)
export NDW_E2E_OUT=$tmp/shots
trap '"$harness" stop; rm -rf "$tmp"' EXIT

# shellcheck source=e2e/render-lib.sh
. "$here/render-lib.sh"

# render <shot> <general.theme value> <GTK_THEME>
render() {
    write_config "$2"
    NDW_E2E_CONFIG=$tmp/config.toml NDW_E2E_GTK_THEME=$3 "$harness" start >/dev/null
    populate
    "$harness" overlay switch
    "$harness" shot "$1" >/dev/null
    check_warnings "$2"
    "$harness" stop
    echo "rendered $1" >&2
}

# section <title> <shot> <theme value as written in config.toml> [css file to show]
section() {
    printf '\n## %s\n\n```toml\n[general]\ntheme = "%s"\n```\n\n![%s](themes/%s.png)\n' "$1" "$3" "$1" "$2"
    if [[ -n ${4:-} ]]; then
        printf '\n<details>\n<summary><code>%s</code></summary>\n\n```css\n%s\n```\n\n</details>\n' \
            "${4#"$repo"/}" "$(cat "$4")"
    fi
}

mkdir -p "$NDW_E2E_OUT"

{
    cat <<'MD'
<!-- Generated by e2e/render-themes.sh; do not edit. -->
# Theme gallery

Set `general.theme` to one of the built-in names, or to the path of a CSS
file. See [Theming](../README.md#theming) for the variables and classes.
MD

    # The default comes first; it follows the GTK theme, so show it under both variants.
    render gtk-dark gtk Default:dark
    section "gtk, under a dark GTK theme" gtk-dark gtk
    render gtk-light gtk Default:light
    section "gtk, under a light GTK theme" gtk-light gtk

    for css in "$repo"/themes/*.css; do
        name=$(basename "$css" .css)
        # gtk.css is done above; gtk-*.css are support files.
        [[ $name == gtk || $name == gtk-* ]] && continue
        # Under GTK's light variant: a self-contained palette must not depend on it.
        render "$name" "$name" Default:light
        section "$name" "$name" "$name" "$css"
    done
} >"$tmp/themes.md"

rm -rf "$shots"
mv "$NDW_E2E_OUT" "$shots"
mv "$tmp/themes.md" "$gallery"
echo "wrote ${gallery#"$repo"/}" >&2
