#!/usr/bin/env bash
# Render every theme in themes/ into docs/themes/<name>.png and regenerate docs/themes.md.
# Run inside 'nix develop' after 'cargo build'.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo=$(dirname "$here")
harness=$here/harness.sh
gallery=$repo/docs/themes.md
shots=$repo/docs/themes

# Everything lands in a scratch dir first, so a failed run leaves docs/ untouched.
tmp=$(mktemp -d)
export NDW_E2E_OUT=$tmp/shots
trap '"$harness" stop; rm -rf "$tmp"' EXIT

# The focused and urgent cards are named after their state, for people comparing themes.
declare -A names=([w]=web [e]=mail [a]=active [s]=frontend [d]=docs [c]=chat [n]=urgent)

# render <shot> <general.theme value> <GTK_THEME>
render() {
    local shot=$1 theme=$2 key
    {
        # hide_empty_static drops niri's trailing empty workspace from the row above the keyboard.
        sed "s|^\[general\]|[general]\ntheme = \"$theme\"\nhide_empty_static = true|" "$here/fixtures/config.toml"
        for key in "${!names[@]}"; do
            printf '\n[workspace.%s]\nname = "%s"\n' "$key" "${names[$key]}"
        done
    } >"$tmp/config.toml"

    NDW_E2E_CONFIG=$tmp/config.toml NDW_E2E_GTK_THEME=$3 "$harness" start >/dev/null
    for key in w e s d c n; do
        "$harness" app switch "$key"
    done
    # Urgency belongs to windows, and focusing one clears it: open one on n, leave, then flag it.
    "$harness" run foot sh -c 'sleep 60' >/dev/null 2>&1 &
    local window
    until window=$("$harness" run niri msg -j windows | jq -er '.[0].id'); do
        sleep 0.1
    done
    "$harness" app switch a
    "$harness" run niri msg action set-window-urgent --id "$window"
    "$harness" overlay switch
    "$harness" shot "$shot" >/dev/null
    # An unknown name or broken CSS still opens the overlay, just with the wrong colours.
    local warnings
    warnings=$("$harness" logs 50 | grep "config warning:\|theme warning:\|Theme pars" | sort -u || true)
    if [[ -n $warnings ]]; then
        echo "$warnings" >&2
        echo "render-themes: '$theme' did not load cleanly" >&2
        exit 1
    fi
    "$harness" stop
    echo "rendered $shot" >&2
}

# section <title> <shot> <theme value as written in config.toml> [css file to show]
section() {
    printf '\n## %s\n\n```toml\n[general]\ntheme = "%s"\n```\n\n![%s](themes/%s.png)\n' "$1" "$3" "$1" "$2"
    if [[ -n ${4:-} ]]; then
        printf '\n<details>\n<summary><code>%s</code></summary>\n\n```css\n%s\n```\n\n</details>\n' \
            "${4#"$repo"/}" "$(cat "$4")"
    fi
}

mkdir -p "$NDW_E2E_OUT"

{
    cat <<'MD'
<!-- Generated by e2e/render-themes.sh; do not edit. -->
# Theme gallery

Set `general.theme` to one of the built-in names, or to the path of a CSS
file. See [Theming](../README.md#theming) for the variables and classes.
MD

    # The default comes first; it follows the GTK theme, so show it under both variants.
    render gtk-dark gtk Default:dark
    section "gtk, under a dark GTK theme" gtk-dark gtk
    render gtk-light gtk Default:light
    section "gtk, under a light GTK theme" gtk-light gtk

    for css in "$repo"/themes/*.css; do
        name=$(basename "$css" .css)
        # gtk.css is done above; gtk-*.css are support files.
        [[ $name == gtk || $name == gtk-* ]] && continue
        # Under GTK's light variant: a self-contained palette must not depend on it.
        render "$name" "$name" Default:light
        section "$name" "$name" "$name" "$css"
    done
} >"$tmp/themes.md"

rm -rf "$shots"
mv "$NDW_E2E_OUT" "$shots"
mv "$tmp/themes.md" "$gallery"
echo "wrote ${gallery#"$repo"/}" >&2
